name: npm-publish
on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - run: npm ci
        env:
          HUSKY: 0
      - run: npm test
        env:
          HUSKY: 0
      - run: npm run build
        env:
          HUSKY: 0
      - uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: public